import { useEffect, useRef, useState } from "react";
import { api, ApiError, isAbort } from "./api";
import { ErrorNotice, PageHeading, ROLE_LABELS } from "./shared";
import type { ManagedAccount, Role } from "./types";

function AccountEditor({ account, principalId, onSaved, onRefresh, onIdentityChanged }: { account: ManagedAccount; principalId: string; onSaved: (account: ManagedAccount) => void; onRefresh: () => void; onIdentityChanged: () => Promise<void> | void }) {
  const [role, setRole] = useState<Role>(account.role); const [enabled, setEnabled] = useState(account.enabled); const [busy, setBusy] = useState(false); const [blocked, setBlocked] = useState(false); const [error, setError] = useState<unknown>(null); const [notice, setNotice] = useState<string | null>(null); const lock = useRef(false);
  async function save() {
    if (lock.current || blocked) return; lock.current = true; setBusy(true); setError(null); setNotice(null);
    try { const updated = await api.updateAccount(account.id, account.version, role, enabled); onSaved(updated); setNotice("账号权限已保存。"); if (updated.id === principalId) await onIdentityChanged(); }
    catch (caught) { setError(caught); if (caught instanceof ApiError && caught.status === 409 && (caught.code === "account_version_conflict" || caught.code === "account_version_changed")) { setBlocked(true); setNotice("记录已被更新，请刷新账号版本后再保存。"); } else if (caught instanceof ApiError && caught.code === "last_enabled_admin") setNotice("企业需要至少一位可用管理员，请保留该账号的管理员权限。"); else if (!(caught instanceof ApiError) || caught.status === 0 || caught.status >= 500) { setBlocked(true); setNotice("保存结果暂时未知，请刷新账号版本核对后再操作。"); } }
    finally { lock.current = false; setBusy(false); }
  }
  return <article className="detail-panel" aria-label="账号权限详情"><span className="section-kicker">ACCOUNT PERMISSIONS</span><h2>{account.display_name}</h2><p className="detail-meta">版本 {account.version} · {account.id === principalId ? "当前登录账号" : "企业成员"}</p><p className="field-help">角色决定工作台与知识资料的访问范围。禁用账号会立即停止该账号使用服务。</p><ErrorNotice error={error} />{notice ? <p className="action-notice" role="status">{notice}</p> : null}<fieldset className="management-form" disabled={busy}><label>账号角色<select value={role} onChange={(event) => setRole(event.target.value as Role)}><option value="employee">员工</option><option value="support">支持专员</option><option value="admin">管理员</option></select></label><label className="confirmation-check"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} />允许使用此账号</label><button className="primary-button" disabled={blocked || (role === account.role && enabled === account.enabled)} onClick={save}>{busy ? "正在保存" : "保存账号权限"}</button></fieldset><button className="secondary-button" disabled={busy} onClick={onRefresh}>刷新账号版本</button></article>;
}

export default function AccountsPage({ principalId, onIdentityChanged }: { principalId: string; onIdentityChanged: () => Promise<void> | void }) {
  const [accounts, setAccounts] = useState<ManagedAccount[]>([]); const [selected, setSelected] = useState<string | null>(null); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null); const [refresh, setRefresh] = useState(0); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError(null);
    api.accounts(undefined, controller.signal).then((result) => { if (controller.signal.aborted) return; setAccounts(result.items); setCursor(result.next_cursor); setSelected((current) => result.items.some((account) => account.id === current) ? current : result.items[0]?.id ?? null); }).catch((caught: unknown) => { if (!isAbort(caught)) setError(caught); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [refresh]);
  async function more() { if (!cursor || loading) return; setLoading(true); setError(null); try { const result = await api.accounts(cursor); setAccounts((current) => [...current, ...result.items.filter((item) => !current.some((existing) => item.id === existing.id))]); setCursor(result.next_cursor); } catch (caught) { setError(caught); } finally { setLoading(false); } }
  const account = accounts.find((item) => item.id === selected);
  return <section className="production-page"><PageHeading kicker="ENTERPRISE ACCESS" title="账号管理" description="管理已通过企业登录的成员，调整角色或暂停账号访问。" /><div className="button-row"><button disabled={loading} onClick={() => { setNotice(null); setRefresh((value) => value + 1); }}>刷新账号列表</button></div><ErrorNotice error={error} onRetry={() => setRefresh((value) => value + 1)} />{notice ? <p className="action-notice" role="status">{notice}</p> : null}<div className="record-detail-layout"><div className="record-list" aria-label="企业账号列表">{accounts.map((item) => <button className={item.id === selected ? "record-row selected" : "record-row"} key={item.id} onClick={() => { setSelected(item.id); setNotice(null); }}><strong>{item.display_name}</strong><small>{ROLE_LABELS[item.role]}</small><span className={`status-badge status-${item.enabled ? "active" : "inactive"}`}>{item.enabled ? "可用" : "已禁用"}</span></button>)}{loading ? <p role="status">正在加载账号…</p> : !accounts.length ? <p className="empty-note">暂无企业成员。</p> : null}{cursor ? <button disabled={loading} onClick={more}>加载更多账号</button> : null}</div>{account ? <AccountEditor key={`${account.id}-${account.version}`} account={account} principalId={principalId} onSaved={(updated) => { setAccounts((current) => current.map((item) => item.id === updated.id ? updated : item)); setNotice("账号权限已保存。"); }} onRefresh={() => { setNotice(null); setRefresh((value) => value + 1); }} onIdentityChanged={onIdentityChanged} /> : <div className="detail-panel workspace-empty"><h3>选择成员管理访问权限</h3></div>}</div></section>;
}
