import { useEffect, useRef, useState } from "react";
import { api, isAbort } from "./api";
import { dateTime, ErrorNotice, PageHeading, StatusBadge } from "./shared";
import TicketsPage from "./TicketsPage";
import type { Assignee, Escalation } from "./types";
import { EscalationDetails } from "./EscalationDetails";

function EscalationCard({ record, assignees, onUpdated, onOpenSource }: { record: Escalation; assignees: Assignee[]; onUpdated: (record: Escalation) => void; onOpenSource: (id: string, revision?: string) => void }) {
  const [expanded, setExpanded] = useState(false);
  const [status, setStatus] = useState(record.status); const [assignee, setAssignee] = useState(record.assignee_id ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null); const lock = useRef(false);
  useEffect(() => { setStatus(record.status); setAssignee(record.assignee_id ?? ""); setError(null); }, [record.version, record.status, record.assignee_id]);
  async function save() { if (lock.current) return; lock.current = true; setBusy(true); setError(null); try { onUpdated(await api.updateEscalation(record, status, assignee || null)); } catch (caught) { setError(caught); } finally { lock.current = false; setBusy(false); } }
  return <article className="escalation-card"><div className="card-title-row"><div><span className="section-kicker">ESCALATION / V{record.version}</span><h3>人工支持请求</h3></div><StatusBadge status={record.status} /></div><p className="article-text">{record.reason === "explicit_manual_request" ? "员工明确请求人工支持" : record.reason === "restricted_request" ? "需要身份与权限核验" : record.reason}</p><p className="detail-meta">员工 {record.user_id} · {dateTime(record.created_at)}</p><small>会话 {record.conversation_id} · 运行 {record.run_id}</small><ErrorNotice error={error} /><fieldset className="management-form" disabled={busy}><label>升级处理人<select value={assignee} onChange={(event) => setAssignee(event.target.value)}><option value="">未分派</option>{assignees.map((user) => <option key={user.id} value={user.id}>{user.display_name}</option>)}</select></label><label>升级状态<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="pending">待处理</option><option value="in_progress">处理中</option><option value="resolved">已解决</option><option value="closed">已关闭</option></select></label><button className="primary-button" disabled={status === record.status && assignee === (record.assignee_id ?? "")} onClick={save}>{busy ? "正在保存" : "保存升级处理"}</button></fieldset><button className="secondary-button" aria-expanded={expanded} onClick={() => setExpanded((value) => !value)}>{expanded ? "收起交接明细" : "查看交接上下文与处理记录"}</button>{expanded ? <EscalationDetails id={record.id} version={record.version} onOpenSource={onOpenSource} /> : null}</article>;
}
export default function SupportPage({ onOpenSource = () => {} }: { onOpenSource?: (id: string, revision?: string) => void }) {
  const [escalations, setEscalations] = useState<Escalation[]>([]); const [assignees, setAssignees] = useState<Assignee[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<unknown>(null); const [refresh, setRefresh] = useState(0); const [tab, setTab] = useState<"escalations" | "tickets">("escalations");
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); Promise.all([api.escalations(undefined, controller.signal), api.assignees(controller.signal)]).then(([result, users]) => { if (controller.signal.aborted) return; setEscalations(result.escalations); setCursor(result.next_cursor); setAssignees(users.users); }).catch((caught: unknown) => { if (!isAbort(caught)) setError(caught); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [refresh]);
  async function more() { if (!cursor || loading) return; setLoading(true); try { const result = await api.escalations(cursor); setEscalations((current) => [...current, ...result.escalations.filter((item) => !current.some((existing) => item.id === existing.id))]); setCursor(result.next_cursor); } catch (caught) { setError(caught); } finally { setLoading(false); } }
  return <section className="production-page"><PageHeading kicker="SUPPORT DESK" title="支持工作台" description="接收人工升级请求，分派责任人，跟进工单和处理审计。" /><div className="page-tabs" role="tablist" aria-label="支持队列"><button role="tab" aria-selected={tab === "escalations"} onClick={() => setTab("escalations")}>升级队列</button><button role="tab" aria-selected={tab === "tickets"} onClick={() => setTab("tickets")}>企业工单</button></div>{tab === "tickets" ? <TicketsPage role="support" embedded assignedUsers={assignees} /> : <><div className="button-row"><button disabled={loading} onClick={() => setRefresh((value) => value + 1)}>刷新升级队列</button></div><ErrorNotice error={error} onRetry={() => setRefresh((value) => value + 1)} />{loading ? <p role="status">正在加载升级队列…</p> : null}<div className="escalation-grid">{escalations.map((record) => <EscalationCard key={record.id} record={record} assignees={assignees} onOpenSource={onOpenSource} onUpdated={(updated) => setEscalations((current) => current.map((item) => item.id === updated.id ? updated : item))} />)}</div>{!loading && !escalations.length ? <p className="empty-note">暂无人工升级请求。</p> : null}{cursor ? <button disabled={loading} onClick={more}>加载更多升级请求</button> : null}</>}</section>;
}
