"""Production identity durable runs tickets and knowledge revisions

Revision ID: 0003_production_engineering
Revises: 0002_observability_feedback
Create Date: 2026-10-02 00:59:17.249117
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003_production_engineering'
down_revision: Union[str, None] = '0002_observability_feedback'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_knowledge_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_model_budgets',
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('spent', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('production_ticket_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('identity_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject', name='uq_identity_issuer_subject'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('production_business_audits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_business_audits_entity_id'), 'production_business_audits', ['entity_id'], unique=False)
    op.create_table('production_knowledge_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['production_knowledge_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_knowledge_jobs_status'), 'production_knowledge_jobs', ['status'], unique=False)
    op.create_table('production_knowledge_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('collection_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('embedding_revision', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_name')
    )
    op.create_table('production_escalations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_production_escalations_user_id'), 'production_escalations', ['user_id'], unique=False)
    op.create_table('production_knowledge_active_pointer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['production_knowledge_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_knowledge_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['production_knowledge_sources.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['production_knowledge_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'document_id', 'chunk_index', name='uq_production_revision_chunk')
    )
    op.create_index(op.f('ix_production_knowledge_chunks_revision_id'), 'production_knowledge_chunks', ['revision_id'], unique=False)
    op.create_table('production_knowledge_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('access_level', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['production_knowledge_sources.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['production_knowledge_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'document_id', name='uq_production_knowledge_snapshot_document')
    )
    op.create_index(op.f('ix_production_knowledge_snapshots_revision_id'), 'production_knowledge_snapshots', ['revision_id'], unique=False)
    op.create_table('production_ticket_drafts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_nonce', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ticket_number', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_production_ticket_drafts_conversation_id'), 'production_ticket_drafts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_production_ticket_drafts_user_id'), 'production_ticket_drafts', ['user_id'], unique=False)
    op.create_table('production_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('result_message_id', sa.String(length=64), nullable=True),
    sa.Column('client_message_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('user_access_level', sa.String(length=50), nullable=False),
    sa.Column('index_revision', sa.String(length=64), server_default='', nullable=False),
    sa.Column('next_sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('worker_id', sa.String(length=200), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget_month', sa.String(length=7), nullable=False),
    sa.Column('reserved_cost', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('settled_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('input_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('output_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'client_message_id', name='uq_production_run_client_message'),
    sa.UniqueConstraint('message_id'),
    sa.UniqueConstraint('result_message_id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_production_run_idempotency')
    )
    op.create_index('ix_production_run_lease', 'production_runs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_production_run_queue', 'production_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_production_runs_conversation_id'), 'production_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_production_runs_trace_id'), 'production_runs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_production_runs_user_id'), 'production_runs', ['user_id'], unique=False)
    op.create_index('uq_production_run_active_conversation', 'production_runs', ['conversation_id'], unique=True, postgresql_where=sa.text("status IN ('queued','running')"))
    op.create_table('production_tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_number', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attempted_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assignee_id', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['production_ticket_drafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_index(op.f('ix_production_tickets_user_id'), 'production_tickets', ['user_id'], unique=False)
    op.create_table('production_run_events',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['production_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'sequence')
    )
    op.create_table('production_ticket_comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['production_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_ticket_comments_ticket_id'), 'production_ticket_comments', ['ticket_id'], unique=False)
    op.create_table('production_ticket_confirmations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['production_tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_production_ticket_confirmations_owner_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_ticket_confirmations')
    op.drop_index(op.f('ix_production_ticket_comments_ticket_id'), table_name='production_ticket_comments')
    op.drop_table('production_ticket_comments')
    op.drop_table('production_run_events')
    op.drop_index(op.f('ix_production_tickets_user_id'), table_name='production_tickets')
    op.drop_table('production_tickets')
    op.drop_index('uq_production_run_active_conversation', table_name='production_runs', postgresql_where=sa.text("status IN ('queued','running')"))
    op.drop_index(op.f('ix_production_runs_user_id'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_trace_id'), table_name='production_runs')
    op.drop_index(op.f('ix_production_runs_conversation_id'), table_name='production_runs')
    op.drop_index('ix_production_run_queue', table_name='production_runs')
    op.drop_index('ix_production_run_lease', table_name='production_runs')
    op.drop_table('production_runs')
    op.drop_index(op.f('ix_production_ticket_drafts_user_id'), table_name='production_ticket_drafts')
    op.drop_index(op.f('ix_production_ticket_drafts_conversation_id'), table_name='production_ticket_drafts')
    op.drop_table('production_ticket_drafts')
    op.drop_index(op.f('ix_production_knowledge_snapshots_revision_id'), table_name='production_knowledge_snapshots')
    op.drop_table('production_knowledge_snapshots')
    op.drop_index(op.f('ix_production_knowledge_chunks_revision_id'), table_name='production_knowledge_chunks')
    op.drop_table('production_knowledge_chunks')
    op.drop_table('production_knowledge_active_pointer')
    op.drop_index(op.f('ix_production_escalations_user_id'), table_name='production_escalations')
    op.drop_table('production_escalations')
    op.drop_table('production_knowledge_revisions')
    op.drop_index(op.f('ix_production_knowledge_jobs_status'), table_name='production_knowledge_jobs')
    op.drop_table('production_knowledge_jobs')
    op.drop_index(op.f('ix_production_business_audits_entity_id'), table_name='production_business_audits')
    op.drop_table('production_business_audits')
    op.drop_table('identity_accounts')
    op.drop_table('production_ticket_counters')
    op.drop_table('production_model_budgets')
    op.drop_table('production_knowledge_sources')
    # ### end Alembic commands ###
