"""production_index_jobs_and_account_controls

Revision ID: 7faac2b3f1a9
Revises: 0003_production_engineering
Create Date: 2026-10-02 01:28:43.476165
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7faac2b3f1a9'
down_revision: Union[str, None] = '0003_production_engineering'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_knowledge_index_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('request_key', sa.String(length=200), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('target_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(length=100), nullable=True),
    sa.Column('staging_collections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index(op.f('ix_production_knowledge_index_jobs_status'), 'production_knowledge_index_jobs', ['status'], unique=False)
    op.add_column('identity_accounts', sa.Column('role_override', sa.String(length=50), nullable=True))
    op.add_column('identity_accounts', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('identity_accounts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('production_knowledge_jobs', sa.Column('index_job_id', sa.String(length=64), nullable=True))
    op.create_foreign_key('fk_knowledge_job_index_job', 'production_knowledge_jobs', 'production_knowledge_index_jobs', ['index_job_id'], ['id'])
    op.add_column('production_knowledge_revisions', sa.Column('dimensions', sa.Integer(), nullable=True))
    op.add_column('production_knowledge_revisions', sa.Column('pipeline_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Previously published indexes have no pipeline manifest. Do not silently certify them.
    # They must be rebuilt before serving production queries.
    op.execute("UPDATE production_knowledge_revisions SET dimensions=CASE WHEN embedding_model ~ '^deterministic:[0-9]+$' THEN split_part(embedding_model,':',2)::integer ELSE 512 END, pipeline_config=jsonb_build_object('version',0,'requires_rebuild',true)")
    op.alter_column('production_knowledge_revisions','dimensions',nullable=False)
    op.alter_column('production_knowledge_revisions','pipeline_config',nullable=False)
    op.add_column('production_knowledge_sources', sa.Column('index_job_id', sa.String(length=64), nullable=True))
    op.create_foreign_key('fk_knowledge_source_index_job', 'production_knowledge_sources', 'production_knowledge_index_jobs', ['index_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_knowledge_source_index_job', 'production_knowledge_sources', type_='foreignkey')
    op.drop_column('production_knowledge_sources', 'index_job_id')
    op.drop_column('production_knowledge_revisions', 'pipeline_config')
    op.drop_column('production_knowledge_revisions', 'dimensions')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_knowledge_job_index_job', 'production_knowledge_jobs', type_='foreignkey')
    op.drop_column('production_knowledge_jobs', 'index_job_id')
    op.drop_column('identity_accounts', 'updated_at')
    op.drop_column('identity_accounts', 'version')
    op.drop_column('identity_accounts', 'role_override')
    op.drop_index(op.f('ix_production_knowledge_index_jobs_status'), table_name='production_knowledge_index_jobs')
    op.drop_table('production_knowledge_index_jobs')
    # ### end Alembic commands ###
