"""Actual isolated PG/Qdrant contracts for reviewed Markdown and old revisions."""
import hashlib
import importlib.util
from pathlib import Path
from types import SimpleNamespace
from uuid import uuid4

from fastapi import HTTPException
import pytest
from qdrant_client import models
from sqlalchemy import select

from app.production.business import now
from app.production.identity import Principal
from app.production.knowledge import build_retriever, document_detail, documents, revision_collection
from app.production.knowledge_models import KnowledgeActivePointer, KnowledgeJob, KnowledgeRevision, KnowledgeSnapshot, KnowledgeSource, RevisionChunk
from app.rag.ingest import DeterministicEmbedder
from tests.production.test_knowledge_snapshots import knowledge_context  # shared disposable fixture


PARSER = "markdown-it-py-4.2.0-structure-v1"


def v1_config():
    # Frozen manifest copied from the pre-change source, not generated by v2.
    return {"version": 1, "max_chars": 800, "overlap_chars": 120, "tokenizer": "cjk-bigram-latin-v1",
        "pdf_extraction": "ruled-cells-normalized-page-context-v2", "pdf_chunking": "atomic-row-page-v1", "max_table_chars": 800,
        "legacy_pdf_policy": "exclude-unlocated-sources-v1", "normalize_embeddings": True, "query_instruction": "",
        "distance": "Cosine", "reranker": "lexical-v1", "vector_weight": 0.65, "bm25_weight": 0.35,
        "minimum_evidence_score": 0.35}


async def publish(c, filename, text, access="employee", title="Generic guide"):
    job = await c.service.enqueue_upload(c.owner, filename, title, access, text.encode())
    await c.service.process_job(job["id"])
    preview = await c.service.job_detail(job["id"])
    assert preview["status"] == "ready", preview["error"]
    result = await c.service.execute_publish(c.owner, job["id"])
    return job, preview, result


async def legacy(c):
    content = "# Legacy\n\n## Old steps\n\nLegacy procedure: inspect the cable.\n"
    raw = "Legacy procedure: inspect the cable."
    document_id, revision_id, chunk_id = str(uuid4()), str(uuid4()), str(uuid4())
    collection = revision_collection(c.settings.qdrant_collection, revision_id)
    vector = (await DeterministicEmbedder(dimensions=32).encode(["Legacy\n" + raw]))[0]
    await c.qdrant.create_collection(collection_name=collection,
        vectors_config=models.VectorParams(size=32, distance=models.Distance.COSINE))
    await c.qdrant.upsert(collection_name=collection, wait=True, points=[models.PointStruct(id=chunk_id, vector=vector,
        payload={"document_id": document_id, "access_level": "employee", "revision_id": revision_id})])
    digest = hashlib.sha256(content.encode()).hexdigest()
    async with c.factory.begin() as session:
        session.add(KnowledgeSource(id=document_id, title="Legacy", source_path="old.md", content_hash=digest,
            content=content, access_level="employee", status="active", version=1))
        session.add(KnowledgeRevision(id=revision_id, collection_name=collection, status="ready", document_count=1,
            chunk_count=1, embedding_model="deterministic:32", embedding_revision="sha256-token-v1", dimensions=32,
            pipeline_config=v1_config(), created_by=c.owner))
        await session.flush()
        session.add(KnowledgeSnapshot(revision_id=revision_id, document_id=document_id, title="Legacy", source_path="old.md",
            content=content, content_hash=digest, access_level="employee"))
        start = content.index(raw)
        session.add(RevisionChunk(id=chunk_id, revision_id=revision_id, document_id=document_id, chunk_index=0,
            content=raw, source_title="Legacy", source_path="old.md", char_start=start, char_end=start + len(raw), access_level="employee"))
        session.add(KnowledgeActivePointer(id=1, revision_id=revision_id))
    return SimpleNamespace(document_id=document_id, revision_id=revision_id, chunk_id=chunk_id,
        content=content, raw=raw, digest=digest, collection=collection)


@pytest.mark.asyncio
async def test_reviewed_markdown_structure_is_persisted_and_used_for_actual_index_inputs(knowledge_context, monkeypatch):
    import app.production.knowledge as module
    c = knowledge_context
    encoded = []
    class CapturingEmbedder(DeterministicEmbedder):
        async def encode(self, texts):
            encoded.extend(texts)
            return await super().encode(texts)
    embedder = CapturingEmbedder(dimensions=32)
    monkeypatch.setattr(module, "build_embedder", lambda settings: embedder)
    text = "# Guide\n\n## RoomBox B200 E-42\n\n```sh\n# literal comment\n\necho inspect\n```\n"
    job, preview, result = await publish(c, "new.md", text)
    assert preview["sections"][0]["section_path"] == ["Guide", "RoomBox B200 E-42"]
    async with c.factory() as session:
        revision = await session.get(KnowledgeRevision, result["revision_id"])
        rows = list(await session.scalars(select(RevisionChunk).where(RevisionChunk.revision_id == revision.id)))
        source = await session.scalar(select(KnowledgeSource).where(KnowledgeSource.source_path == "new.md"))
        snapshot = await session.scalar(select(KnowledgeSnapshot).where(KnowledgeSnapshot.revision_id == revision.id))
    assert revision.pipeline_config["version"] == 2
    assert revision.pipeline_config["markdown_parser"] == PARSER
    assert source.parser_version == snapshot.parser_version == PARSER
    assert len(rows) == 1 and rows[0].structure["section_path"] == ["Guide", "RoomBox B200 E-42"]
    assert text[rows[0].char_start:rows[0].char_end] == rows[0].content
    assert encoded == ["Generic guide\n章节：Guide > RoomBox B200 E-42\n" + rows[0].content]
    points, _ = await c.qdrant.scroll(collection_name=revision.collection_name, limit=10, with_payload=True)
    assert points[0].payload["structure"] == rows[0].structure
    assert (await c.service.job_detail(job["id"]))["status"] == "published"


@pytest.mark.asyncio
async def test_unknown_old_markdown_is_not_relabelled_or_automatically_added_to_new_pipeline(knowledge_context):
    c = knowledge_context
    old = await legacy(c)
    _, _, result = await publish(c, "new.md", "# New\n\nCurrent procedure.")
    assert result["excluded_documents"] == ["old.md"]
    async with c.factory() as session:
        source = await session.get(KnowledgeSource, old.document_id)
        old_chunk = await session.get(RevisionChunk, old.chunk_id)
        old_revision = await session.get(KnowledgeRevision, old.revision_id)
        paths = list(await session.scalars(select(KnowledgeSnapshot.source_path).where(KnowledgeSnapshot.revision_id == result["revision_id"])))
    assert paths == ["new.md"]
    assert source.content == old.content and source.content_hash == old.digest and source.parser_version is None
    assert old_chunk.content == old.raw and old_chunk.structure is None and old_revision.pipeline_config == v1_config()
    assert (await c.qdrant.count(collection_name=old.collection, exact=True)).count == 1
    request = SimpleNamespace(app=SimpleNamespace(state=SimpleNamespace(knowledge_service=c.service)))
    listing = await documents(request, principal=Principal(c.owner, "Admin", "admin"))
    row = next(row for row in listing["documents"] if row["id"] == old.document_id)
    assert row["requires_reparse"] is True and row["reparse_reason"] == "markdown_structure"
    historical = await build_retriever(c.factory, c.qdrant, c.settings, old.revision_id)
    assert (await historical.retrieve("Legacy procedure", user_access_level="employee"))[0].citation.index_revision == old.revision_id
    assert (await c.service.activate_revision(c.owner, old.revision_id))["revision_id"] == old.revision_id


@pytest.mark.asyncio
async def test_old_snapshot_is_readable_without_inventing_new_parser_identity(knowledge_context):
    c = knowledge_context
    old = await legacy(c)
    request = SimpleNamespace(app=SimpleNamespace(state=SimpleNamespace(knowledge_service=c.service)))
    article = await document_detail(old.document_id, request, Principal("employee", "Employee", "employee"), index_revision=old.revision_id)
    assert article["content"] == old.content
    assert article.get("parser_version") is None
    assert all(section.get("parser_version") is None for section in article["sections"])


@pytest.mark.asyncio
async def test_same_bytes_can_be_prepared_reviewed_and_published_without_rewriting_old_snapshot(knowledge_context, tmp_path):
    c = knowledge_context
    old = await legacy(c)
    corpus = tmp_path / "corpus"
    corpus.mkdir()
    (corpus / "old.md").write_bytes(old.content.encode())
    spec = importlib.util.spec_from_file_location("markdown_upgrade_import", Path(__file__).resolve().parents[3] / "scripts/ingest_knowledge.py")
    cli = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(cli)
    args = cli.build_parser().parse_args(["--directory", str(corpus), "--actor-id", c.owner, "--dry-run"])
    assert (await cli.prepare_production(args, c.settings, c.factory, c.service))[0]["status"] == "would_enqueue"
    args.dry_run = False
    prepared = await cli.prepare_production(args, c.settings, c.factory, c.service)
    assert prepared[0]["status"] == "queued"
    await c.service.process_job(prepared[0]["job_id"])
    await c.service.job_detail(prepared[0]["job_id"])
    result = await c.service.execute_publish(c.owner, prepared[0]["job_id"])
    assert result["revision_id"] != old.revision_id
    assert (await cli.prepare_production(args, c.settings, c.factory, c.service))[0]["status"] == "unchanged"
    async with c.factory() as session:
        snapshot = await session.scalar(select(KnowledgeSnapshot).where(KnowledgeSnapshot.revision_id == old.revision_id))
        source = await session.get(KnowledgeSource, old.document_id)
    assert snapshot.content == old.content and snapshot.parser_version is None
    assert source.content_hash == old.digest and source.parser_version == PARSER
    assert (await build_retriever(c.factory, c.qdrant, c.settings, old.revision_id)).revision.pipeline_config == v1_config()


@pytest.mark.asyncio
async def test_pre_upgrade_ready_job_cannot_publish_without_new_parse_and_preview(knowledge_context):
    c = knowledge_context
    job_id = str(uuid4())
    async with c.factory.begin() as session:
        session.add(KnowledgeJob(id=job_id, user_id=c.owner, title="Old", source_path="unused.md", original_filename="old.md",
            content_hash="0" * 64, access_level="employee", status="ready", content="# Old\n\nOld procedure.",
            sections=[{"heading": "Old", "content": "Old procedure."}], previewed_at=now()))
    detail = await c.service.job_detail(job_id)
    assert detail["requires_reparse"] is True
    with pytest.raises(HTTPException) as denied:
        await c.service.enqueue_publish(c.owner, job_id)
    assert denied.value.status_code == 409
    with pytest.raises(HTTPException) as direct:
        await c.service.execute_publish(c.owner, job_id)
    assert direct.value.status_code == 409 and await c.service.active_revision_id() is None


@pytest.mark.asyncio
async def test_oversize_code_fails_before_publication_and_leaves_active_revision_intact(knowledge_context):
    c = knowledge_context
    old = await legacy(c)
    text = "# Guide\n\n```sh\n" + "x" * 801 + "\n```"
    job = await c.service.enqueue_upload(c.owner, "oversize.md", "Oversize", "employee", text.encode())
    await c.service.process_job(job["id"])
    detail = await c.service.job_detail(job["id"])
    assert detail["status"] == "failed" and "上限" in detail["error"]
    with pytest.raises(HTTPException):
        await c.service.execute_publish(c.owner, job["id"])
    assert await c.service.active_revision_id() == old.revision_id
    async with c.factory() as session:
        assert list(await session.scalars(select(KnowledgeSource.source_path))) == ["old.md"]


@pytest.mark.asyncio
async def test_structure_prefixes_stay_in_same_document_permissions_and_recheck_current_role(knowledge_context, monkeypatch):
    c = knowledge_context
    for filename, code, role in [("employee.md", "EMP-101", "employee"), ("support.md", "SUP-202", "support"), ("admin.md", "ADM-303", "admin")]:
        await publish(c, filename, f"# Operations\n\n## {code}\n\nInspect the matching device.", role)
    retriever = await build_retriever(c.factory, c.qdrant, c.settings)
    employee = await retriever.retrieve("ADM-303", user_access_level="employee")
    assert {hit.citation.source_path for hit in employee} <= {"employee.md"}
    support = await retriever.retrieve("SUP-202", user_access_level="support")
    assert support[0].citation.source_path == "support.md"
    admin = await retriever.retrieve("ADM-303", user_access_level="admin")
    assert admin[0].citation.source_path == "admin.md"
    original_query = c.qdrant.query_points
    async def tighten_access(**kwargs):
        result = await original_query(**kwargs)
        async with c.factory.begin() as session:
            source = await session.scalar(select(KnowledgeSource).where(KnowledgeSource.source_path == "employee.md"))
            source.access_level = "admin"
        return result
    monkeypatch.setattr(c.qdrant, "query_points", tighten_access)
    assert await retriever.retrieve("EMP-101", user_access_level="employee") == []


@pytest.mark.asyncio
async def test_legacy_compatibility_does_not_accept_tampered_manifest_or_another_model(knowledge_context):
    c = knowledge_context
    old = await legacy(c)
    assert (await build_retriever(c.factory, c.qdrant, c.settings, old.revision_id)).revision.id == old.revision_id
    async with c.factory.begin() as session:
        revision = await session.get(KnowledgeRevision, old.revision_id)
        revision.pipeline_config = {**v1_config(), "minimum_evidence_score": 0.01}
    with pytest.raises(ValueError, match="differs"):
        await build_retriever(c.factory, c.qdrant, c.settings, old.revision_id)
    async with c.factory.begin() as session:
        revision = await session.get(KnowledgeRevision, old.revision_id)
        revision.pipeline_config = v1_config()
        revision.embedding_model = "unapproved-model"
    with pytest.raises(HTTPException) as denied:
        await c.service.activate_revision(c.owner, old.revision_id)
    assert denied.value.status_code == 409


@pytest.mark.asyncio
async def test_token_budget_failure_happens_before_qdrant_or_active_pointer_side_effect(knowledge_context, monkeypatch):
    import app.production.knowledge as module
    import app.rag.ingest as ingestion
    c = knowledge_context
    old = await legacy(c)
    _, _, initial = await publish(c, "reviewed.md", "# Reviewed\n\nA previously reviewed procedure.")
    job = await c.service.enqueue_upload(c.owner, "new.md", "New", "employee", b"# New\n\nAnother procedure.")
    await c.service.process_job(job["id"])
    await c.service.job_detail(job["id"])
    vector_creates = []
    original_create = c.qdrant.create_collection
    async def tracked_create(**kwargs):
        vector_creates.append(kwargs["collection_name"])
        return await original_create(**kwargs)
    class BudgetFailure(DeterministicEmbedder):
        async def token_counts(self, texts):
            error_type = getattr(ingestion, "EmbeddingInputTooLong", ValueError)
            raise error_type("完整输入超过512 token上限，请人工整理。")
    monkeypatch.setattr(module, "build_embedder", lambda settings: BudgetFailure(dimensions=32))
    monkeypatch.setattr(c.qdrant, "create_collection", tracked_create)
    task = await c.service.enqueue_publish(c.owner, job["id"])
    await c.service.process_next_job()
    detail = await c.service.index_job_detail(task["id"])
    assert detail["status"] == "failed" and detail["error"] == "embedding_input_too_long"
    assert vector_creates == []
    assert await c.service.active_revision_id() == initial["revision_id"]
    assert (await c.qdrant.count(collection_name=old.collection, exact=True)).count == 1
    async with c.factory() as session:
        assert await session.scalar(select(KnowledgeSource).where(KnowledgeSource.source_path == "new.md")) is None
